name: Deploiement de mon projet dans Google Cloud

on:
  push:
    branches:
      - main  # Déclenche l'action sur les push dans la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout source code
      uses: actions/checkout@v3

    # Étape 2 : Configurer l'environnement Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Installation de pytest pour exécuter les tests

    # Étape 4 : Exécuter les tests
    - name: Run tests
      run: |
        pytest test_unitaire_API.py

    # Étape 5 : Configurer l'authentification Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Étape 6 : Configurer le projet Google Cloud
    - name: Set Google Cloud project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Étape 7 : Déployer sur Google App Engine
    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet   